### ISSUE TITLE
请问一下关于dubbo连接问题

### ISSUE THREAD

**Issue by Feeeenng** [ravenq/ravenq.github.io#1]
我的duboo机器 192.168.0.1
tomcat 192.168.0.2
tomcat docker-compose中也是按照您的文档中设置相关参数
```yaml
    environment:
      #JAVA_OPTS: "-Djava.security.egd=file:/dev/./urandom"
      Dubbo_IP_TO_REGISTRY: 192.168.0.2  
      Dubbo_PORT_TO_REGISTRY: 41897
      DUBBO_PORT_TO_BIND: 41897
```
设置了以后，连接的始终是容器内部的ip
请问是我缺少了什么吗
